/** Every in-app URL in one place. Client users' screens live under /portal. */
export const paths = {
  home: '/',
  login: '/login',
  changePassword: '/change-password',
  account: '/account',
  myWork: '/my-work',
  notifications: '/notifications',
  clients: '/clients',
  client: (id: string) => `/clients/${id}`,
  project: (key: string, tab = 'board') => `/projects/${key}/${tab}`,
  ticket: (key: string) => `/tickets/${key}`,
  pitches: '/pitches',
  pitch: (id: string) => `/pitches/${id}`,
  meetings: '/meetings',
  meeting: (id: string) => `/meetings/${id}`,
  page: (id: string) => `/pages/${id}`,
  pageEdit: (id: string) => `/pages/${id}/edit`,
  adminUsers: '/admin/users',
  adminUser: (id: string) => `/admin/users/${id}`,
  adminAudit: '/admin/audit',
  portal: {
    home: '/portal',
    notifications: '/portal/notifications',
    account: '/portal/account',
    pitch: (id: string) => `/portal/pitches/${id}`,
    page: (id: string) => `/portal/pages/${id}`,
    meeting: (id: string) => `/portal/meetings/${id}`,
  },
};
